import React, { useState, useEffect } from 'react';
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
import DocUploader from '../components/DocUploader';
import ChatBox from '../components/ChatBox';

export default function Dashboard({ user, onLogout, apiBase, theme, toggleTheme }) {
  const [activeTab, setActiveTab] = useState('summarizer'); 
  const [activeNav, setActiveNav] = useState('dashboard');
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  
  const [docResult, setDocResult] = useState(null);
  const [uploadStep, setUploadStep] = useState(-1);
  const [uploadError, setUploadError] = useState('');
  

  const [isProcessing, setIsProcessing] = useState(false);
  
  const [redactedDocContext, setRedactedDocContext] = useState('');
  
  const [recentDocs, setRecentDocs] = useState(() => {
    const saved = sessionStorage.getItem('smartlaw_recent_docs');
    return saved ? JSON.parse(saved) : [];
  });

  useEffect(() => {
    const savedActiveDoc = sessionStorage.getItem('smartlaw_active_doc');
    if (savedActiveDoc) {
      try {
        const parsed = JSON.parse(savedActiveDoc);
        setDocResult(parsed.result);
        setUploadStep(parsed.step);
        if (parsed.result?.redacted_text) {
           setRedactedDocContext(parsed.result.redacted_text);
        }
      } catch(e) {}
    }
  }, []);

  useEffect(() => {
    sessionStorage.setItem('smartlaw_recent_docs', JSON.stringify(recentDocs));
  }, [recentDocs]);
  
  useEffect(() => {
    if (docResult && uploadStep === 3) {
      sessionStorage.setItem('smartlaw_active_doc', JSON.stringify({ result: docResult, step: uploadStep }));
    }
  }, [docResult, uploadStep]);

  const handleDocumentReady = (result) => {
    setDocResult(result);
    setRedactedDocContext(result.redacted_text);
    setRecentDocs(prev => [{ 
      id: Date.now(), 
      name: result.filename || `Document ${prev.length + 1}`, 
      result: result 
    }, ...prev]);
    setActiveTab('summarizer');
    setActiveNav('dashboard');
  };

  const loadRecentDoc = (doc) => {
    if (doc && doc.result) {
      setDocResult(doc.result);
      setRedactedDocContext(doc.result.redacted_text);
      setUploadStep(3); 
      setActiveTab('summarizer');
      setActiveNav('dashboard');
    }
  };

  const handleDownloadPDF = (title, content) => {
    const printWindow = window.open('', '', 'height=600,width=800');
    if (!printWindow) { alert("Please allow popups for PDF export."); return; }
    printWindow.document.write('<html><head><title>' + title + '</title>');
    printWindow.document.write('<style>body{font-family:serif;padding:40px;line-height:1.6;color:#222;}.header{text-align:center;border-bottom:2px solid #000;margin-bottom:30px;padding-bottom:10px;}.footer{margin-top:50px;font-size:10px;color:#777;text-align:center;border-top:1px solid #ccc;padding-top:10px;}.pill{display:inline-block;padding:2px 8px;background:#eee;border-radius:4px;font-size:12px;margin-bottom:10px;}pre{white-space:pre-wrap;font-family:serif;font-size:14px;}</style>');
    printWindow.document.write('</head><body>');
    printWindow.document.write('<div class="header"><h1>SmartLaw AI</h1><p>Professional Legal Intelligence & Analysis</p></div>');
    printWindow.document.write('<div class="pill">File: ' + title + '</div>');
    printWindow.document.write('<div><pre>' + content + '</pre></div>');
    printWindow.document.write('<div class="footer"><p>This document was generated by SmartLaw. ⚖️ Disclaimer: AI-generated draft/summary. Review before use.</p></div>');
    printWindow.document.write('</body></html>');
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  const renderContent = () => {
    if (activeNav === 'library') {
      return (
        <div style={{ padding: '1rem' }}>
          <h3 style={{ marginBottom: '1rem' }}>📚 Legal Template Library</h3>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '1.5rem' }}>Select a template to generate and analyze a draft instantly.</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '1.25rem' }}>
            {[
              { name: 'NDA - Non Disclosure', icon: '🔒', desc: 'Confidentiality rules, data protection, and trade secret matter.' },
              { name: 'Service Agreement', icon: '🤝', desc: 'Scope of work, payment terms, and liability regulations.' },
              { name: 'Employment Contract', icon: '👔', desc: 'Labor laws, compensation structure, and termination clauses.' },
              { name: 'Rental Agreement', icon: '🏠', desc: 'Rent control acts, security deposits, and maintenance rules.' },
              { name: 'Sales Deed', icon: '📜', desc: 'Property transfer laws and registration requirements.' },
              { name: 'General Affidavit', icon: '📝', desc: 'Legal declarations, oaths, and evidence procedures.' },
              { name: 'Power of Attorney', icon: '⚖️', desc: 'Authority delegation and agency representation rules.' },
              { name: 'Will & Testament', icon: '💎', desc: 'Succession laws, asset distribution, and probate matter.' },
              { name: 'Gift Deed', icon: '🎁', desc: 'Transfer of Property Act and tax implication rules.' }
            ].map(t => (
              <div 
                key={t.name} 
                className="glass-card-hover" 
                style={{ padding: '1.5rem', cursor: 'pointer', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}
                onClick={() => {
                  setUploadStep(1); 
                  setActiveNav('dashboard');
                  setActiveTab('summarizer');
                  
                  fetch(`${apiBase}/document/chat`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${user.token}` },
                    body: JSON.stringify({ query: `Draft a professional ${t.name} template for Indian Law. Return ONLY the document text.` })
                  })
                  .then(res => res.json())
                  .then(draftData => {
                    if (!draftData.answer) throw new Error("Drafting failed.");
                    const draftedResult = {
                      summary: draftData.answer,
                      risk_level: "LOW",
                      redacted_text: draftData.answer,
                      filename: t.name,
                      char_count: draftData.answer.length,
                      pii_found: false
                    };
                    handleDocumentReady(draftedResult);
                    setUploadStep(3);
                  })
                  .catch(err => {
                    console.error("Drafting error", err);
                    setUploadError("Drafting failed. Try again.");
                    setUploadStep(-1);
                  });
                }}
              >
                 <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.25rem' }}>
                    <span style={{ fontSize: '1.5rem' }}>{t.icon}</span>
                    <p style={{ fontWeight: 700, fontSize: '0.95rem', margin: 0 }}>{t.name}</p>
                 </div>
                 <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', lineHeight: 1.5, flex: 1 }}>{t.desc}</p>
                 <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '0.5rem' }}>
                    <span style={{ fontSize: '0.75rem', fontWeight: 600, color: 'var(--gold-light)' }}>Analyze Draft →</span>
                    <span className="badge badge-gold" style={{ fontSize: '0.65rem', padding: '2px 6px' }}>Template</span>
                 </div>
              </div>
            ))}
          </div>
        </div>
      );
    }

    if (activeNav === 'chat') {
      return (
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', height: '100%' }}>
          <ChatBox token={user?.token} apiBase={apiBase} redactedContext={redactedDocContext} recentDocs={recentDocs} onSelectContext={(text) => setRedactedDocContext(text)} />
        </div>
      );
    }

    // DASHBOARD (Summarizer)
    return (
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflowY: 'auto' }}>
        {docResult && uploadStep === 3 && (
            <button className="btn-ghost" style={{ alignSelf: 'flex-end', marginBottom: '1rem', fontSize: '0.8rem' }} onClick={() => handleDownloadPDF(docResult.filename || "Summary", docResult.summary)}>
               💾 Save Summary as PDF
            </button>
        )}
        <div style={redactedDocContext ? {} : { padding: '2rem 0', margin: 'auto', width: '100%' }}>
          <DocUploader token={user?.token} apiBase={apiBase} onSummaryReady={handleDocumentReady} step={uploadStep} setStep={setUploadStep} result={docResult} setResult={setDocResult} error={uploadError} setError={setUploadError} />
        </div>
      </div>
    );
  };

  return (
    <div className="app-layout">
      {isSidebarOpen && <div className="mobile-overlay" onClick={() => setIsSidebarOpen(false)}></div>}
      <Sidebar 
        user={user} 
        activeNav={activeNav} 
        recentDocs={recentDocs} 
        isOpen={isSidebarOpen}
        onClose={() => setIsSidebarOpen(false)}
        onLoadDoc={(doc) => { setActiveNav('dashboard'); loadRecentDoc(doc); setIsSidebarOpen(false); }} 
        onNavChange={(nav) => { setActiveNav(nav); setIsSidebarOpen(false); }} 
      />
      <main style={{ flex: 1, display: 'flex', flexDirection: 'column', height: '100vh', overflowY: 'auto' }}>
        <Navbar user={user} onLogout={onLogout} onMenuClick={() => setIsSidebarOpen(true)} theme={theme} toggleTheme={toggleTheme} />
        <div style={{ maxWidth: 900, width: '100%', margin: '0 auto', padding: '2.5rem 1.5rem', flex: 1, display: 'flex', flexDirection: 'column' }}>
          <div className="fade-up" style={{ marginBottom: '1.5rem' }}>
            <h2 style={{ fontSize: '1.75rem', fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'Playfair Display, serif' }}>Welcome back, {user?.name?.split(' ')[0]} 👋</h2>
          </div>
          
          <div className="glass-card fade-up" style={{ flex: 1, display: 'flex', flexDirection: 'column', padding: (activeNav === 'chat') ? 0 : '1.75rem', overflow: 'hidden' }}>
             {renderContent()}
          </div>
        </div>
      </main>
    </div>
  );
}
