import React, { useState, useEffect } from 'react';
import Sidebar from '../components/Sidebar';
import Navbar from '../components/Navbar';
import DocUploader from '../components/DocUploader';

export default function Dashboard({ user, onLogout, theme, toggleTheme, apiBase }) {
  const [activeNav, setActiveNav] = useState('dashboard');
  const [recentDocs, setRecentDocs] = useState([]);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  
  const [docResult, setDocResult] = useState(null);
  const [uploadStep, setUploadStep] = useState(-1);
  const [uploadError, setUploadError] = useState('');
  const [initialResultTab, setInitialResultTab] = useState('summary');
  
  const [isProcessing, setIsProcessing] = useState(false);
  
  const [redactedDocContext, setRedactedDocContext] = useState('');

  useEffect(() => {
    if (user?.token) {
      fetch(`${apiBase}/document/history`, {
        headers: { 'Authorization': `Bearer ${user.token}` }
      })
      .then(res => res.json())
      .then(data => { if (Array.isArray(data)) setRecentDocs(data); })
      .catch(err => console.error("History fetch failed:", err));
    }
  }, [user, apiBase]);

  const loadRecentDoc = (doc) => {
    setDocResult(doc);
    setUploadStep(3);
    setRedactedDocContext(doc.redacted_text);
    setInitialResultTab('summary');
  };

  const handleDownloadPDF = (title, content) => {
    const printWindow = window.open('', '', 'height=600,width=800');
    printWindow.document.write('<html><head><title>SmartLaw AI - ' + title + '</title>');
    printWindow.document.write('<style>body{font-family:serif;padding:40px;color:#333;line-height:1.6;}.header{text-align:center;border-bottom:2px solid #000;margin-bottom:30px;padding-bottom:10px;}.footer{margin-top:50px;border-top:1px solid #eee;padding-top:10px;font-size:12px;text-align:center;color:#666;}.pill{display:inline-block;padding:4px 12px;background:#f0f0f0;border-radius:20px;font-size:12px;margin-bottom:20px;}</style>');
    printWindow.document.write('</head><body>');
    printWindow.document.write('<div class="header"><h1>SmartLaw AI</h1><p>Professional Legal Intelligence & Analysis</p></div>');
    printWindow.document.write('<div class="pill">File: ' + title + '</div>');
    printWindow.document.write('<div><pre style="white-space:pre-wrap;font-family:serif;font-size:14px;">' + content + '</pre></div>');
    printWindow.document.write('<div class="footer"><p>This document was generated by SmartLaw. ⚖️ Disclaimer: AI-generated draft/summary. Review before use.</p></div>');
    printWindow.document.write('</body></html>');
    printWindow.document.close();
    setTimeout(() => {
      printWindow.focus();
      printWindow.print();
    }, 500);
  };

  const handleDocumentReady = (result, defaultTab = 'summary') => {
    setDocResult(result);
    setRedactedDocContext(result.redacted_text);
    setInitialResultTab(defaultTab);
    setRecentDocs(prev => [{ 
      id: Date.now(), 
      name: result.filename || `Document ${prev.length + 1}`, 
      date: new Date().toLocaleDateString(),
      ...result 
    }, ...prev]);
    setActiveNav('dashboard');
  };

  const renderContent = () => {
    if (activeNav === 'library') {
      const templates = [
        { name: "Non-Disclosure Agreement (NDA)", desc: "Confidentiality terms for business discussions.", prompt: "Generate a professional Non-Disclosure Agreement (NDA) between two parties including non-solicitation and data protection clauses." },
        { name: "Service Agreement", desc: "Terms for freelance or consulting services.", prompt: "Draft a Service Agreement for a consultant providing technical services, including payment terms, IP ownership, and termination clauses." },
        { name: "Rental/Lease Agreement", desc: "For residential or commercial properties.", prompt: "Create a residential rental agreement including security deposit, maintenance responsibilities, and notice period." },
        { name: "Employment Contract", desc: "Standard terms for hiring employees.", prompt: "Draft an employment contract including roles, salary, confidentiality, and non-compete clauses." },
        { name: "Legal Notice for Recovery", desc: "Demand letter for unpaid dues.", prompt: "Draft a formal legal notice for recovery of unpaid dues from a client, including a 15-day notice period." }
      ];
      return (
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflowY: 'auto', padding: '1rem' }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '1.25rem' }}>
            {templates.map(t => (
              <div key={t.name} className="glass-card" style={{ padding: '1.5rem', border: '1px solid var(--border)', transition: 'transform 0.2s' }}>
                <h3 style={{ fontSize: '1.1rem', marginBottom: '0.5rem', color: 'var(--gold-light)' }}>{t.name}</h3>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '1.25rem' }}>{t.desc}</p>
                <button className="btn-gold" style={{ width: '100%' }} disabled={isProcessing} onClick={() => {
                  setIsProcessing(true);
                  fetch(`${apiBase}/document/chat`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${user.token}` },
                    body: JSON.stringify({ query: t.prompt, history: [] })
                  })
                  .then(res => res.json())
                  .then(draftData => {
                    const draftedResult = {
                      summary: draftData.answer,
                      redacted_text: draftData.answer,
                      filename: t.name,
                      char_count: draftData.answer.length,
                      pii_found: false
                    };
                    handleDocumentReady(draftedResult, 'document');
                    setUploadStep(3);
                  })
                  .catch(err => { console.error("Template draft failed:", err); alert("Failed to generate template."); })
                  .finally(() => setIsProcessing(false));
                }}>
                  {isProcessing ? 'Generating...' : 'Use Template'}
                </button>
              </div>
            ))}
          </div>
        </div>
      );
    }

    if (activeNav === 'chat') {
      return (
        <iframe 
          src="/chat-embed" 
          style={{ width: '100%', height: '100%', border: 'none', borderRadius: 'var(--radius-md)' }} 
          title="AI Legal Assistant"
        />
      );
    }

    // Default Dashboard (Summarizer)
    return (
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflowY: 'auto' }}>
        {docResult && uploadStep === 3 && (
            <button className="btn-ghost" style={{ alignSelf: 'flex-end', marginBottom: '1rem', fontSize: '0.8rem' }} onClick={() => handleDownloadPDF(docResult.filename || "Summary", docResult.summary)}>
               💾 Save Summary as PDF
            </button>
        )}
        <div style={redactedDocContext ? { flex: 1, display: 'flex', flexDirection: 'column' } : { padding: '2rem 0', margin: 'auto', width: '100%' }}>
          <DocUploader token={user?.token} apiBase={apiBase} onSummaryReady={handleDocumentReady} step={uploadStep} setStep={setUploadStep} result={docResult} setResult={setDocResult} error={uploadError} setError={setUploadError} initialTab={initialResultTab} />
        </div>
      </div>
    );
  };

  return (
    <div className="app-layout" style={{ height: '100vh', overflow: 'hidden' }}>
      {isSidebarOpen && <div className="mobile-overlay" onClick={() => setIsSidebarOpen(false)}></div>}
      <Sidebar 
        user={user} 
        activeNav={activeNav} 
        recentDocs={recentDocs} 
        isOpen={isSidebarOpen}
        onClose={() => setIsSidebarOpen(false)}
        onLoadDoc={(doc) => { setActiveNav('dashboard'); loadRecentDoc(doc); setIsSidebarOpen(false); }} 
        onNavChange={(nav) => { setActiveNav(nav); setIsSidebarOpen(false); }} 
      />
      <main style={{ flex: 1, display: 'flex', flexDirection: 'column', height: '100vh', overflow: 'hidden', background: 'var(--bg-base)' }}>
        <Navbar user={user} onLogout={onLogout} onMenuClick={() => setIsSidebarOpen(true)} theme={theme} toggleTheme={toggleTheme} />
        
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', padding: '1.5rem', overflow: 'hidden' }}>
          <div style={{ maxWidth: 1200, width: '100%', margin: '0 auto', flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
            <div className="fade-up" style={{ marginBottom: '1rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <h2 style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'Playfair Display, serif', margin: 0 }}>
                {activeNav === 'dashboard' ? 'Dashboard Hub' : activeNav === 'library' ? 'Template Library' : 'AI Legal Chat'}
              </h2>
              <div className="badge badge-gold">
                 {activeNav.toUpperCase()}
              </div>
            </div>
            
            <div className="glass-card fade-up" style={{ flex: 1, display: 'flex', flexDirection: 'column', padding: (activeNav === 'chat') ? 0 : '1.5rem', overflow: 'hidden', border: '1px solid var(--border)', background: 'var(--bg-surface)' }}>
               {renderContent()}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
